export const IMAGES_3D = [
    {
        path: '/images/works/aguasinvaso2x.jpg',
        bigpath: '',
        title: 'Water Simulation',
        category: 'Simulation',
        desc: 'Water and gas simulation for advertising and industrial reels',
    },
    {
        path: '/images/works/algobot2x.jpg',
        bigpath: '',
        title: 'Algobot',
        category: 'Filostros',
        desc: 'Filostros y Forlayos project',
    },
    {
        path: '/images/works/aliengracioso2x.jpg',
        bigpath: '',
        title: 'Alien',
        category: '3D Character',
        desc: 'Sculpting concept of an alien.',
    },
    {
        path: '/images/works/archvizkitchen2x.jpg',
        bigpath: '',
        title: 'Archviz Kitchen',
        category: '3D Archviz Concept',
        desc: 'Archviz interior of a modern kitchen.',
    },
    {
        path: '/images/works/firewarmod2x.jpg',
        bigpath: '',
        title: 'Fire-War HL2 Mod',
        category: 'Lead 3D Designer',
        desc: 'A several work in progress pics of the discontinued Half-Life 2 Mod: Fire-War.',
    },
    {
        path: '/images/works/bigshelter2x.jpg',
        bigpath: '',
        title: 'Virtual-Tour 3D Archviz',
        category: '3D Virtual-Tour',
        desc: 'A 3d web Virtual-Tour for Rising S Shelters, showing the Aristocrat model.',
    },
    {
        path: '/images/works/conferenceroom2x.jpg',
        bigpath: '',
        title: 'Conference Room 360º',
        category: '3D Virtual-Tour',
        desc: 'An archviz virtual conference room for 360 or VR.',
    },
    {
        path: '/images/works/coronavirusinthebasement2x.jpg',
        bigpath: '',
        title: 'In the basement',
        category: '3D Animation',
        desc: 'A short 3D animation with a big coronavirus falling down the stairs.',
    },
    {
        path: '/images/works/crawleyedgeboatshed2x.jpg',
        bigpath: '',
        title: 'Crawley\'s Edge Boatshed',
        category: '3D Archviz',
        desc: 'A 3D photo realist archviz of typical Crawley\'s Edge Boatshed.',
    },
    {
        path: '/images/works/crybabies2x.jpg',
        bigpath: '',
        title: 'CryBabies Character',
        category: '3D Characters',
        desc: 'An example of Crybabies cartoonish styled character.',
    },
    {
        path: '/images/works/fictionalfragance2x.jpg',
        bigpath: '',
        title: 'Fictional Fragance',
        category: '3D Product',
        desc: 'A fictional 3D ad for a fragance.',
    },
    {
        path: '/images/works/fooddronedelivery2x.jpg',
        bigpath: '',
        title: 'Drone Delivery',
        category: '3D Concept',
        desc: 'A 3D concept from environment in a dystopian near future.',
    },
]

export const IMAGES_FRONTEND = [
    
]

export const IMAGES_VIDEOVFX = [
    {
        path: '/images/works/aguilabook2x.jpg',
        bigpath: '',
        title: 'Wild Eagle',
        category: 'Photobook',
        desc: 'Photo report about eagles from wildlife',
    },
    {
        path: '/images/works/amsterdambikes2x.jpg',
        bigpath: '',
        title: 'Amsterdam Travel',
        category: 'Photobook',
        desc: 'Amsterdam travel photoshoot',
    },
    {
        path: '/images/works/buenafuente2x.jpg',
        bigpath: '',
        title: 'Buenafuente Sketches',
        category: 'Video & VFX',
        desc: 'A couple of humour sketches, mixing chroma video footage from Andreu Buenafuente\'s En El Aire late night show.',
    },
    {
        path: '/images/works/altamirano2x.jpg',
        bigpath: '',
        title: 'Altamirano\'s Downhill',
        category: 'Video Promo',
        desc: 'Video promotion for Altamirano\'s Downhill Team & Shop.',
    },
    {
        path: '/images/works/barconerja2x.jpg',
        bigpath: '',
        title: 'Archviz Kitchen',
        category: 'Photo Report',
        desc: 'Photo report from the Spain\'s south coast.',
    },
    {
        path: '/images/works/bca2x.jpg',
        bigpath: '',
        title: 'BCA Tutorials',
        category: 'Video Production',
        desc: 'A series of video tutorials focused to B2B clients.',
    },
    {
        path: '/images/works/bodacostumbrista2x.jpg',
        bigpath: '',
        title: 'BCA Tutorials',
        category: 'Event Video & Photo',
        desc: 'Photobooks for Weddings and other family events with a different point of view.',
    },
    {
        path: '/images/works/bookperra2x.jpg',
        bigpath: '',
        title: 'Dog Portrait',
        category: 'Animal Photoshoot',
        desc: 'Animal photobooks with natural, posed and funny styles.',
    },
    {
        path: '/images/works/bikecampo2x.jpg',
        bigpath: '',
        title: 'A Bike\'s Day',
        category: 'Lifestyle Photo',
        desc: 'An example of hundreds of lifestyle photo sesions for branding.',
    },
    {
        path: '/images/works/caballoarbol2x.jpg',
        bigpath: '',
        title: 'Traditional Farming',
        category: 'Lifestyle Photo',
        desc: 'A photo reportage about traditional farming at Pyrenees.',
    },
    {
        path: '/images/works/caballoretrato2x.jpg',
        bigpath: '',
        title: 'Millan\'s Horse',
        category: 'Lifestyle Photo',
        desc: 'Photobook with a funny horse.',
    },
    {
        path: '/images/works/caprichogaudi2x.jpg',
        bigpath: '',
        title: 'Capricho de Gaudí',
        category: 'Lifestyle Photo',
        desc: 'The winner HDR picture from the Capricho de Gaudí building photography contest, placed in Comillas, Cantabria.',
    },
    {
        path: '/images/works/catalogocolonia2x.jpg',
        bigpath: '',
        title: 'Dirty English',
        category: 'Product Photoshoot',
        desc: 'Photo catalog for Dirty English fragance by Juicy Couture.',
    },
    {
        path: '/images/works/catalogopocketmgz2x.jpg',
        bigpath: '',
        title: 'Glasses Catalog',
        category: 'Product Photoshoot',
        desc: 'A lifestyle photoshoot for a glasses product placement for Pocket Magazine.',
    },
    {
        path: '/images/works/cerroskate2x.jpg',
        bigpath: '',
        title: 'Cerro\'s Skate',
        category: 'Video Promo',
        desc: 'A video promo for Jorge Cerro freestyle skater.',
    },
    {
        path: '/images/works/chema12x.jpg',
        bigpath: '',
        title: 'Chema Sales Booklet',
        category: 'Photo / Booklet',
        desc: 'Photoshoot, editing and design of the CD booklet for Chema Sales.',
    },
    {
        path: '/images/works/chevrolet2x.jpg',
        bigpath: '',
        title: 'Chevrolet Bel Air',
        category: 'Lifestyle Photo',
        desc: 'Classic cars photoshoots for enthusiast owners.',
    },
    {
        path: '/images/works/chicharrocd2x.jpg',
        bigpath: '',
        title: '\'La Caja de las Ánimas\'',
        category: 'Photo / Booklet',
        desc: 'Photoshoot and booklet design for \'La Caja de las Ánimas\' album from Guillermo Chicharro.',
    },
    {
        path: '/images/works/chicharrostudio2x.jpg',
        bigpath: '',
        title: 'Chicharro\'s Studio',
        category: 'Pressbook Photo',
        desc: 'Photoshoots of different music studios like KMC or Lizard Studios.',
    },
    {
        path: '/images/works/comillas2x.jpg',
        bigpath: '',
        title: 'Shore Landscape',
        category: 'Natural Photoshoot',
        desc: 'HDR Photoshoots of landscapes and natural views.',
    },
    {
        path: '/images/works/composicionfondos2x.jpg',
        bigpath: '',
        title: 'Background replacement',
        category: 'Video / VFX',
        desc: 'Background replacements for films, shortfilms and tv shows.',
    },
    {
        path: '/images/works/deilamanita2x.jpg',
        bigpath: '',
        title: '\'Deil\'',
        category: 'Video Shortfilm',
        desc: 'Color correction for award-winning DEIL shortfilm by Amanita Films.',
    },
    {
        path: '/images/works/docuhealingnotes2x.jpg',
        bigpath: '',
        title: '\'The Healing Notes\'',
        category: 'Video Documentary',
        desc: 'Color correction for award-winning DEIL shortfilm by Amanita Films.',
    },
    {
        path: '/images/works/dorange2x.jpg',
        bigpath: '',
        title: 'd\'Orange Unplugged',
        category: 'Video Music Clip',
        desc: 'Unplugged song videoclip for dOrange band.',
    },
    {
        path: '/images/works/dronefreestyle2x.jpg',
        bigpath: '',
        title: 'Drone Freestyle',
        category: 'Aerial Video',
        desc: 'FPV Drone Freestyling videos.',
    },
    {
        path: '/images/works/eventpeople2x.jpg',
        bigpath: '',
        title: 'Family Events',
        category: 'Photoshoot',
        desc: 'Stylized photo books from events.',
    },
    {
        path: '/images/works/finistere2x.jpg',
        bigpath: '',
        title: 'Finisterre\'s Cape',
        category: 'Photoshoot',
        desc: 'Photo reportage from the \'end of the earth\', Finisterre.',
    },
    {
        path: '/images/works/freebord2x.jpg',
        bigpath: '',
        title: 'Freebord Skates',
        category: 'Video Promo',
        desc: 'An inspirational video promo for the Freebord skates user experience.',
    },
    {
        path: '/images/works/gondwana22x.jpg',
        bigpath: '',
        title: 'Musician Portrait',
        category: 'Photo / Booklet',
        desc: 'Photoshoots for mucisians book.',
    },
    {
        path: '/images/works/greentotem12x.jpg',
        bigpath: '',
        title: 'The Green Totem I',
        category: 'Motion Graphics',
        desc: 'Content depending intro mo-graph animations..',
    },
    {
        path: '/images/works/greentotem22x.jpg',
        bigpath: '',
        title: 'The Green Totem II',
        category: 'Motion Graphics',
        desc: 'Content depending intro mo-graph animations..',
    },
    {
        path: '/images/works/greentotem32x.jpg',
        bigpath: '',
        title: 'The Green Totem III',
        category: 'Motion Graphics',
        desc: 'Content depending intro mo-graph animations..',
    },
    {
        path: '/images/works/haitioptimista2x.jpg',
        bigpath: '',
        title: 'The Green Totem III',
        category: 'Motion Graphics',
        desc: 'Content depending intro mo-graph animations..',
    },
]