export const IMAGES_3D = [
    {
        path: '/images/works/aguasinvaso.jpg',
        bigpath: '/images/works/g-',
        title: 'Water Simulation',
        category: 'Simulation',
        desc: 'Water and gas simulation for advertising and industrial reels',
    },
    {
        path: '/images/works/algobot.jpg',
        bigpath: '/images/works/g-',
        title: 'Algobot',
        category: 'Filostros',
        desc: 'Filostros y Forlayos project',
    },
    {
        path: '/images/works/aliengracioso.jpg',
        bigpath: '/images/works/g-',
        title: 'Alien',
        category: '3D Character',
        desc: 'Sculpting concept of an alien.',
    },
    {
        path: '/images/works/archvizkitchen.jpg',
        bigpath: '/images/works/g-',
        title: 'Archviz Kitchen',
        category: '3D Archviz Concept',
        desc: 'Archviz interior of a modern kitchen.',
    },
    {
        path: '/images/works/firewarmod.jpg',
        bigpath: '/images/works/g-',
        title: 'Fire-War HL2 Mod',
        category: 'Lead 3D Designer',
        desc: 'A several work in progress pics of the discontinued Half-Life 2 Mod: Fire-War.',
    },
    {
        path: '/images/works/bigshelter.jpg',
        bigpath: '/images/works/g-',
        title: 'Virtual-Tour 3D Archviz',
        category: '3D Virtual-Tour',
        desc: 'A 3d web Virtual-Tour for Rising S Shelters, showing the Aristocrat model.',
    },
    {
        path: '/images/works/conferenceroom.jpg',
        bigpath: '/images/works/g-',
        title: 'Conference Room 360º',
        category: '3D Virtual-Tour',
        desc: 'An archviz virtual conference room for 360 or VR.',
    },
    {
        path: '/images/works/coronavirusinthebasement.jpg',
        bigpath: '/images/works/g-',
        title: 'In the basement',
        category: '3D Animation',
        desc: 'A short 3D animation with a big coronavirus falling down the stairs.',
    },
    {
        path: '/images/works/crawleyedgeboatshed.jpg',
        bigpath: '/images/works/g-',
        title: 'Crawley\'s Edge Boatshed',
        category: '3D Archviz',
        desc: 'A 3D photo realist archviz of typical Crawley\'s Edge Boatshed.',
    },
    {
        path: '/images/works/crybabies.jpg',
        bigpath: '/images/works/g-',
        title: 'CryBabies Character',
        category: '3D Characters',
        desc: 'An example of Crybabies cartoonish styled character.',
    },
    {
        path: '/images/works/fictionalfragance.jpg',
        bigpath: '/images/works/g-',
        title: 'Fictional Fragance',
        category: '3D Product',
        desc: 'A fictional 3D ad for a fragance.',
    },
    {
        path: '/images/works/fooddronedelivery.jpg',
        bigpath: '/images/works/g-',
        title: 'Drone Delivery',
        category: '3D Concept',
        desc: 'A 3D concept from environment in a dystopian near future.',
    },
    {
        path: '/images/works/happysquid.jpg',
        bigpath: '/images/works/g-',
        title: 'Happy Squid',
        category: '3D Character',
        desc: 'An example of cartoonish characters.',
    },
    {
        path: '/images/works/icecreamtruck.jpg',
        bigpath: '/images/works/g-',
        title: 'Ice Cream Truck',
        category: '3D Environment',
        desc: 'A 3D concept from a dystopian future cartoon movie for children.',
    },
    {
        path: '/images/works/iscmaskcase.jpg',
        bigpath: '/images/works/g-',
        title: 'ISC Plastics Case',
        category: '3D Product Animation',
        desc: 'An example of industrial product showreel for the mask case of ISC Plastics.',
    },
    {
        path: '/images/works/monumental.jpg',
        bigpath: '/images/works/g-',
        title: 'Monumental Bullring',
        category: '3D Archviz',
        desc: 'A 3D archviz reconstruction of Monumental Bullring in Barcelona.',
    },
    {
        path: '/images/works/moonshortfilm.jpg',
        bigpath: '/images/works/g-',
        title: '\'Moon\'',
        category: '3D Animation Shortfilm',
        desc: '\'Moon\', a 3D animation shortfilm with funny and tiny look.',
    },
    {
        path: '/images/works/museo360.jpg',
        bigpath: '/images/works/g-museo360.jpg',
        title: 'Virtual Museum',
        category: '360 Virtual Tour',
        desc: 'A 3D 360º virtual tour museum for web.',
    },
]

export const IMAGES_FRONTEND = [
    {
        path: '/images/works/web3.jpg',
        bigpath: '/images/works/g-web3.jpg',
        title: 'Personal Porfolios',
        category: 'HTML, CSS, JS',
        desc: 'A portfolio with tasty design.',
    },
    {
        path: '/images/works/web4.jpg',
        bigpath: '/images/works/g-web4.jpg',
        title: 'Universia Santander Shop',
        category: 'HTML, CSS, ASP.NET',
        desc: 'A shop web for book ecommerce.',
    },
    {
        path: '/images/works/web18.jpg',
        bigpath: '/images/works/g-',
        title: 'WMG Pharma',
        category: 'PHP, HTML, CSS',
        desc: 'German Cannabis Pharmaceutical',
    },
    {
        path: '/images/works/web5.jpg',
        bigpath: '/images/works/g-',
        title: 'Puntoblend Community',
        category: 'HTML, CSS, React',
        desc: 'Puntoblend Community portal.',
    },
    {
        path: '/images/works/web6.jpg',
        bigpath: '/images/works/g-',
        title: 'MedievalChess',
        category: 'HTML, SASS, React',
        desc: 'Based on chess but different moves and pieces.',
    },
    {
        path: '/images/works/web19.jpg',
        bigpath: '/images/works/g-',
        title: 'UNED University Shop',
        category: 'XTHML, CSS, ASP.NET',
        desc: 'Web eshop for UNED University.',
    },
    {
        path: '/images/works/web7.jpg',
        bigpath: '/images/works/g-',
        title: 'Travel Japan',
        category: 'HTML, CSS & JS',
        desc: 'Web portal with traveling articles.',
    },
    {
        path: '/images/works/web9.jpg',
        bigpath: '/images/works/g-',
        title: 'Shop Online',
        category: 'HTML, CSS & JS',
        desc: 'Shop web',
    },
    {
        path: '/images/works/web8.jpg',
        bigpath: '/images/works/g-',
        title: 'Bookmark Extension',
        category: 'HTML, CSS, JS',
        desc: 'Bookmark extension web',
    },
    {
        path: '/images/works/web11.jpg',
        bigpath: '/images/works/g-',
        title: 'Mini Game',
        category: 'HTML, CSS, React',
        desc: 'Web for childs to play little options game',
    },
    {
        path: '/images/works/web12.jpg',
        bigpath: '/images/works/g-',
        title: 'Bugdet Calculator',
        category: 'HTML, CSS, React',
        desc: 'Web for business to make budgets',
    },
    {
        path: '/images/works/web13.jpg',
        bigpath: '/images/works/g-',
        title: 'Temporal Job Search',
        category: 'HTML, CSS, React',
        desc: 'Web for job search',
    },
    {
        path: '/images/works/web14.jpg',
        bigpath: '/images/works/g-',
        title: 'Bumpho project',
        category: 'HTML, CSS, JS',
        desc: 'Internet fast search agreggator',
    },
    {
        path: '/images/works/web15.jpg',
        bigpath: '/images/works/g-',
        title: 'Old Portfolios',
        category: 'HTML, CSS, JS',
        desc: 'Old personal portfolio',
    },
    // {
    //     path: '/images/works/web16.jpg',
    //     bigpath: '/images/works/g-',
    //     title: '3D Community web',
    //     category: 'HTML, CSS & JS',
    //     desc: 'Old community portfolio',
    // },
    {
        path: '/images/works/web17.jpg',
        bigpath: '/images/works/g-',
        title: 'TrendsOnUnderground',
        category: 'HTML, CSS, JS',
        desc: 'Underground Trends Community',
    },
    {
        path: '/images/works/web10.jpg',
        bigpath: '/images/works/g-',
        title: 'Jokes page',
        category: 'HTML, CSS, JS',
        desc: 'Jokes page using several API',
    },
    {
        path: '/images/works/web1.jpg',
        bigpath: '/images/works/g-web1.jpg',
        title: 'LMDV Shop',
        category: 'HTML, CSS, JS',
        desc: 'A shop web for ecommerce.',
    },
    {
        path: '/images/works/web2.jpg',
        bigpath: '/images/works/g-web2.jpg',
        title: 'Lick Band Web',
        category: 'HTML, CSS, JS',
        desc: 'A shop web for a music band.',
    },
]

export const IMAGES_VIDEOVFX = [
    {
        path: '/images/works/aguilabook.jpg',
        bigpath: '/images/works/g-',
        title: 'Wild Eagle',
        category: 'Photobook',
        desc: 'Photo report about eagles from wildlife',
    },
    {
        path: '/images/works/amsterdambikes.jpg',
        bigpath: '/images/works/g-',
        title: 'Amsterdam Travel',
        category: 'Photobook',
        desc: 'Amsterdam travel photoshoot',
    },
    {
        path: '/images/works/buenafuente.jpg',
        bigpath: '/images/works/g-',
        title: 'TV Sketches',
        category: 'Video & VFX',
        desc: 'A couple of humour sketches, mixing chroma video footage from Andreu Buenafuente\'s En El Aire late night show.',
    },
    {
        path: '/images/works/altamirano.jpg',
        bigpath: '/images/works/g-',
        title: 'Altamirano\'s Downhill',
        category: 'Video Promo',
        desc: 'Video promotion for Altamirano\'s Downhill Team & Shop.',
    },
    {
        path: '/images/works/barconerja.jpg',
        bigpath: '/images/works/g-',
        title: 'Nerja Ship',
        category: 'Photo Report',
        desc: 'Photo report from the Spain\'s south coast.',
    },
    {
        path: '/images/works/bca.jpg',
        bigpath: '/images/works/g-',
        title: 'BCA Tutorials',
        category: 'Video Production',
        desc: 'A series of video tutorials focused to B2B clients.',
    },
    {
        path: '/images/works/gondwana1.jpg',
        bigpath: '/images/works/g-',
        title: 'Gondwana Album',
        category: 'Photoshoot',
        desc: 'Photo session for the Gondwana album book.',
    },
    {
        path: '/images/works/bodacostumbrista.jpg',
        bigpath: '/images/works/g-',
        title: 'Traditional Events',
        category: 'Event Video & Photo',
        desc: 'Photobooks for Weddings and other family events with a different point of view.',
    },
    {
        path: '/images/works/bookperra.jpg',
        bigpath: '/images/works/g-',
        title: 'Dog Portrait',
        category: 'Animal Photoshoot',
        desc: 'Animal photobooks with natural, posed and funny styles.',
    },
    {
        path: '/images/works/bikecampo.jpg',
        bigpath: '/images/works/g-',
        title: 'A Bike\'s Day',
        category: 'Lifestyle Photo',
        desc: 'An example of hundreds of lifestyle photo sesions for branding.',
    },
    {
        path: '/images/works/caballoarbol.jpg',
        bigpath: '/images/works/g-',
        title: 'Traditional Farming',
        category: 'Lifestyle Photo',
        desc: 'A photo reportage about traditional farming at Pyrenees.',
    },
    {
        path: '/images/works/caballoretrato.jpg',
        bigpath: '/images/works/g-',
        title: 'Millan\'s Horse',
        category: 'Lifestyle Photo',
        desc: 'Photobook with a funny horse.',
    },
    {
        path: '/images/works/caprichogaudi.jpg',
        bigpath: '/images/works/g-',
        title: 'Capricho de Gaudí',
        category: 'Lifestyle Photo',
        desc: 'The winner HDR picture from the Capricho de Gaudí building photography contest, placed in Comillas, Cantabria.',
    },
    {
        path: '/images/works/catalogocolonia.jpg',
        bigpath: '/images/works/g-',
        title: 'Dirty English',
        category: 'Product Photoshoot',
        desc: 'Photo catalog for Dirty English fragance by Juicy Couture.',
    },
    {
        path: '/images/works/catalogopocketmgz.jpg',
        bigpath: '/images/works/g-',
        title: 'Glasses Catalog',
        category: 'Product Photoshoot',
        desc: 'A lifestyle photoshoot for a glasses product placement for Pocket Magazine.',
    },
    {
        path: '/images/works/cerroskate.jpg',
        bigpath: '/images/works/g-',
        title: 'Cerro\'s Skate',
        category: 'Video Promo',
        desc: 'A video promo for Jorge Cerro freestyle skater.',
    },
    {
        path: '/images/works/chema1.jpg',
        bigpath: '/images/works/g-',
        title: 'Chema Sales Booklet',
        category: 'Photo / Booklet',
        desc: 'Photoshoot, editing and design of the CD booklet for Chema Sales.',
    },
    {
        path: '/images/works/chevrolet.jpg',
        bigpath: '/images/works/g-',
        title: 'Chevrolet Bel Air',
        category: 'Lifestyle Photo',
        desc: 'Classic cars photoshoots for enthusiast owners.',
    },
    {
        path: '/images/works/chicharrocd.jpg',
        bigpath: '/images/works/g-',
        title: '\'La Caja de las Ánimas\'',
        category: 'Photo / Booklet',
        desc: 'Photoshoot and booklet design for \'La Caja de las Ánimas\' album from Guillermo Chicharro.',
    },
    {
        path: '/images/works/chicharrostudio.jpg',
        bigpath: '/images/works/g-',
        title: 'Chicharro\'s Studio',
        category: 'Pressbook Photo',
        desc: 'Photoshoots of different music studios like KMC or Lizard Studios.',
    },
    {
        path: '/images/works/comillas.jpg',
        bigpath: '/images/works/g-',
        title: 'Shore Landscape',
        category: 'Natural Photoshoot',
        desc: 'HDR Photoshoots of landscapes and natural views.',
    },
    {
        path: '/images/works/composicionfondos.jpg',
        bigpath: '/images/works/g-',
        title: 'Background replacement',
        category: 'Video / VFX',
        desc: 'Background replacements for films, shortfilms and tv shows.',
    },
    {
        path: '/images/works/deilamanita.jpg',
        bigpath: '/images/works/g-',
        title: '\'Deil\'',
        category: 'Video Shortfilm',
        desc: 'Color correction for award-winning DEIL shortfilm by Amanita Films.',
    },
    {
        path: '/images/works/docuhealingnotes.jpg',
        bigpath: '/images/works/g-',
        title: '\'The Healing Notes\'',
        category: 'Video Documentary',
        desc: 'Color correction for award-winning DEIL shortfilm by Amanita Films.',
    },
    {
        path: '/images/works/dorange.jpg',
        bigpath: '/images/works/g-',
        title: 'd\'Orange Unplugged',
        category: 'Video Music Clip',
        desc: 'Unplugged song videoclip for dOrange band.',
    },
    {
        path: '/images/works/dronefreestyle.jpg',
        bigpath: '/images/works/g-',
        title: 'Drone Freestyle',
        category: 'Aerial Video',
        desc: 'FPV Drone Freestyling videos.',
    },
    {
        path: '/images/works/eventpeople.jpg',
        bigpath: '/images/works/g-',
        title: 'Family Events',
        category: 'Photoshoot',
        desc: 'Stylized photo books from events.',
    },
    {
        path: '/images/works/finistere.jpg',
        bigpath: '/images/works/g-',
        title: 'Finisterre\'s Cape',
        category: 'Photoshoot',
        desc: 'Photo reportage from the \'end of the earth\', Finisterre.',
    },
    {
        path: '/images/works/freebord.jpg',
        bigpath: '/images/works/g-',
        title: 'Freebord Skates',
        category: 'Video Promo',
        desc: 'An inspirational video promo for the Freebord skates user experience.',
    },
    {
        path: '/images/works/gondwana2.jpg',
        bigpath: '/images/works/g-',
        title: 'Musician Portrait',
        category: 'Photo / Booklet',
        desc: 'Photoshoots for mucisians book.',
    },
    {
        path: '/images/works/greentotem1.jpg',
        bigpath: '/images/works/g-',
        title: 'The Green Totem I',
        category: 'Motion Graphics',
        desc: 'Content depending intro mo-graph animations..',
    },
    {
        path: '/images/works/greentotem2.jpg',
        bigpath: '/images/works/g-',
        title: 'The Green Totem II',
        category: 'Motion Graphics',
        desc: 'Content depending intro mo-graph animations..',
    },
    {
        path: '/images/works/greentotem3.jpg',
        bigpath: '/images/works/g-',
        title: 'The Green Totem III',
        category: 'Motion Graphics',
        desc: 'Content depending intro mo-graph animations..',
    },
    {
        path: '/images/works/haitioptimista.jpg',
        bigpath: '/images/works/g-',
        title: 'Haiti Optimista',
        category: 'Photoshoot',
        desc: 'Mixed cameras photo experiment from Haiti\'s childrens for El Pais newspaper and other partners like AECID and Samsung.',
    },
    {
        path: '/images/works/incubusdig.jpg',
        bigpath: '/images/works/g-',
        title: 'Incubus - Dig',
        category: 'Videoclip VFX',
        desc: 'A 3D tracking and replacement for Dig\'s videoclip from Incubus band.',
    },
    {
        path: '/images/works/introspannabis.jpg',
        bigpath: '/images/works/g-',
        title: 'Fairs Coverage',
        category: 'Video Production',
        desc: 'Fairs full coverage for social networks, filming, editing and mo-grap.',
    },
    {
        path: '/images/works/kalifishtanks.jpg',
        bigpath: '/images/works/g-',
        title: 'Kali\'s Fishtanks',
        category: 'Video Book',
        desc: 'Video book of the microbiologist Carlos San Juan\'s Fishtanks with sea and interior ecosystems.',
    },
    {
        path: '/images/works/labrujuladeeva.jpg',
        bigpath: '/images/works/g-',
        title: 'Eva\'s Compass',
        category: 'Video Shortfilm',
        desc: 'Video edit, color, vfx and sounding of Cristina Sardon\'s \'Eva\'s Compass\' shortfilm.',
    },
    {
        path: '/images/works/mrelehaiti.jpg',
        bigpath: '/images/works/g-',
        title: 'M\'Rele Haiti',
        category: 'Video Documentary',
        desc: 'A film documentary in Port Prince and Jacmel in Haiti about childrens life after earthquake.',
    },
]