export const IMAGES_3D = [
    {
        path: '/images/works/aguasinvaso.jpg',
        bigpath: '/images/works/g-aguasinvaso.jpg',
        title: 'Water Simulation',
        category: 'Simulation',
        desc: 'Water and gas simulation for advertising and industrial reels',
    },
    {
        path: '/images/works/windtunnel.jpg',
        bigpath: '/images/works/g-windtunnel.jpg',
        title: 'Wind Tunnel',
        category: '3D Scene',
        desc: 'Wind tunnel scene themed on WWII',
        link: 'https://www.artstation.com/artwork/2882ox',
    },
    {
        path: '/images/works/algobot.jpg',
        bigpath: '/images/works/g-algobot.jpg',
        title: 'Algobot',
        category: '3D Modeling',
        desc: '3D Dog Robopet \'Algobot\' 1º place in 3DSMAX forum competition',
    },
    {
        path: '/images/works/spacetruck.jpg',
        bigpath: '/images/works/g-spacetruck.jpg',
        title: 'Space Truck',
        category: '3D Modeling',
        desc: '3D model of a futuristic Sci-fi Space truck',
        link: 'https://www.artstation.com/artwork/lVoRyY',
    },
    {
        path: '/images/works/mushroomhouse.jpg',
        bigpath: '/images/works/g-mushroomhouse.jpg',
        title: 'Mushroom House',
        category: '3D Modeling',
        desc: '3D model of a mushroom house',
        link: 'https://www.artstation.com/artwork/9ev0nq',
    },
    {
        path: '/images/works/duelmovie.jpg',
        bigpath: '/images/works/g-duelmovie.jpg',
        title: 'Duel Movie Fandom',
        category: '3D Scene',
        desc: '3D scene of a duel between two characters from the movie "Duel"',
        link: 'https://www.artstation.com/artwork/18WZno',
    },
    {
        path: '/images/works/aliengracioso.jpg',
        bigpath: '/images/works/g-aliengracioso.jpg',
        title: 'Alien',
        category: '3D Character',
        desc: 'Sculpting concept of an alien.',
    },
    {
        path: '/images/works/victoriangreenhouse.jpg',
        bigpath: '/images/works/g-victoriangreenhouse.jpg',
        title: 'Victorian Greenhouse',
        category: '3D Modeling',
        desc: '3D model of a Victorian greenhouse',
        link: 'https://www.artstation.com/artwork/58JeoW',
    },
    {
        path: '/images/works/archvizkitchen.jpg',
        bigpath: '/images/works/g-archvizkitchen.jpg',
        title: 'Archviz Kitchen',
        category: '3D Archviz Concept',
        desc: 'Archviz interior of a modern kitchen.',
        link: 'https://www.artstation.com/artwork/PmP4W8',
    },
    {
        path: '/images/works/flybikesrace.jpg',
        bigpath: '/images/works/g-flybikesrace.jpg',
        title: 'Flybikes Race animation',
        category: '3D Animation',
        desc: '3D animation of a Flybikes racing on sci-fi environment',
        link: 'https://www.artstation.com/artwork/v1ezD6',
    },
    {
        path: '/images/works/potionmagicbook.jpg',
        bigpath: '/images/works/potionmagicbook.jpg',
        title: 'Potion Magic Book fandom from Harry Potter',
        category: '3D Asset Realtime',
        desc: '3D Realtime asset of a potion magic book from Harry Potter',
        link: 'https://www.artstation.com/artwork/PmP4W8',
    },
    {
        path: '/images/works/gobletoffire.jpg',
        bigpath: '/images/works/gobletoffire.jpg',
        title: 'Goblet of Fire fandom from Harry Potter',
        category: '3D Asset Realtime',
        desc: '3D Realtime model of a goblet of fire from Harry Potter',
        link: 'https://www.artstation.com/artwork/g25L4G',
    },
    {
        path: '/images/works/gryffindorsword.jpg',
        bigpath: '/images/works/gryffindorsword.jpg',
        title: 'Gryffindor Sword fandom from Harry Potter',
        category: '3D Asset Realtime',
        desc: '3D Realtime model of a sword from Harry Potter',
        link: 'https://www.artstation.com/artwork/3dv39A',
    },
    {
        path: '/images/works/vanishingcabinet.jpg',
        bigpath: '/images/works/vanishingcabinet.jpg',
        title: 'Vanishing Cabinet fandom from Harry Potter',
        category: '3D Asset Realtime',
        desc: '3D Realtime model of a vanishing cabinet from Harry Potter',
        link: 'https://www.artstation.com/artwork/D5mgon',
    },
    {
        path: '/images/works/dumbledorewand.jpg',
        bigpath: '/images/works/dumbledorewand.jpg',
        title: 'Dumbledore\'s Wand fandom from Harry Potter',
        category: '3D Asset Realtime',
        desc: '3D Realtime model of Dumbledore\'s wand from Harry Potter',
        link: 'https://www.artstation.com/artwork/WKGnmG',
    },
    {
        path: '/images/works/scifiweapon.jpg',
        bigpath: '/images/works/scifiweapon.jpg',
        title: 'Sci-fi Weapon',
        category: '3D Asset Realtime',
        desc: '3D Realtime model of a sci-fi weapon',
        link: 'https://www.artstation.com/artwork/D5E549',
    },
    {
        path: '/images/works/oldsubwaystation.jpg',
        bigpath: '/images/works/g-oldsubwaystation.jpg',
        title: 'Old Subway Station',
        category: '3D Scene',
        desc: '3D scene of an old subway station',
        link: 'https://www.artstation.com/artwork/58JYlO',
    },
    {
        path: '/images/works/firewarmod.jpg',
        bigpath: '/images/works/g-firewarmod.jpg',
        title: 'Fire-War HL2 Mod',
        category: 'Lead 3D Designer',
        desc: 'A several work in progress pics of the discontinued Half-Life 2 Mod: Fire-War.',
        link: 'https://www.moddb.com/mods/fire-war/articles',
    },
    {
        path: '/images/works/bigshelter.jpg',
        bigpath: '/images/works/g-bigshelter.jpg',
        title: 'Virtual-Tour 3D Archviz',
        category: '3D Virtual-Tour',
        desc: 'A 3d web Virtual-Tour for Rising S Shelters, showing the Aristocrat model.',
        video: 'gC05T3Hqv0M',
    },
    {
        path: '/images/works/conferenceroom.jpg',
        bigpath: '/images/works/g-conferenceroom.jpg',
        title: 'Conference Room 360º',
        category: '3D Virtual-Tour',
        desc: 'An archviz virtual conference room for 360 or VR.',
        link: 'https://www.artstation.com/artwork/v1ezD6',
    },
    {
        path: '/images/works/coronavirusinthebasement.jpg',
        bigpath: '/images/works/g-coronavirusinthebasement.jpg',
        title: 'In the basement',
        category: '3D Animation',
        desc: 'A short 3D animation with a big coronavirus falling down the stairs.',
        video: 'Ifn_7NawwKA',
    },
    {
        path: '/images/works/crawleyedgeboatshed.jpg',
        bigpath: '/images/works/g-crawleyedgeboatshed.jpg',
        title: 'Crawley\'s Edge Boatshed',
        category: '3D Archviz',
        desc: 'A 3D photo realist archviz of typical Crawley\'s Edge Boatshed.',
        link: 'https://www.artstation.com/artwork/L21akK',
    },
    {
        path: '/images/works/crybabies.jpg',
        bigpath: '/images/works/g-crybabies.jpg',
        title: 'CryBabies Character',
        category: '3D Characters',
        desc: 'An example of Crybabies cartoonish styled character.',
    },
    {
        path: '/images/works/fictionalfragance.jpg',
        bigpath: '/images/works/g-fictionalfragance.jpg',
        title: 'Fictional Fragance',
        category: '3D Product',
        desc: 'A fictional 3D ad for a fragance.',
        link: 'https://www.artstation.com/artwork/N5dq5d',
    },
    {
        path: '/images/works/fooddronedelivery.jpg',
        bigpath: '/images/works/g-fooddronedelivery.jpg',
        title: 'Drone Delivery',
        category: '3D Concept',
        desc: 'A 3D concept from environment in a dystopian near future.',
        link: 'https://www.artstation.com/artwork/mqXOy1',
    },
    {
        path: '/images/works/happysquid.jpg',
        bigpath: '/images/works/g-happysquid.jpg',
        title: 'Happy Squid',
        category: '3D Character',
        desc: 'An example of cartoonish characters.',
        link: 'https://www.artstation.com/artwork/Qzex33',
    },
    {
        path: '/images/works/icecreamtruck.jpg',
        bigpath: '/images/works/g-icecreamtruck.jpg',
        title: 'Ice Cream Truck',
        category: '3D Environment',
        desc: 'A 3D concept from a dystopian future cartoon movie for children.',
        link: 'https://www.artstation.com/artwork/NxxnOq',
    },
    {
        path: '/images/works/iscmaskcase.jpg',
        bigpath: '/images/works/g-iscmaskcase.jpg',
        title: 'ISC Plastics Case',
        category: '3D Product Animation',
        desc: 'An example of industrial product showreel for the mask case of ISC Plastics.',
        link: 'https://www.artstation.com/artwork/68bYRr',
    },
    {
        path: '/images/works/monumental.jpg',
        bigpath: '/images/works/g-monumental.jpg',
        title: 'Monumental Bullring',
        category: '3D Archviz',
        desc: 'A 3D archviz reconstruction of Monumental Bullring in Barcelona.',
    },
    {
        path: '/images/works/moonshortfilm.jpg',
        bigpath: '/images/works/g-moonshortfilm.jpg',
        title: '\'Moon\'',
        category: '3D Animation Shortfilm',
        desc: '\'Moon\', a 3D animation shortfilm with funny and tiny look.',
    },
    {
        path: '/images/works/standpreview.jpg',
        bigpath: '/images/works/g-standpreview.jpg',
        title: '3D Realtime Booth Stand Prev',
        category: '3D Realtime Previz',
        desc: 'A 3D realtime previz of a booth stand.',
        link: 'https://sketchfab.com/3d-models/cultiva-hanfmesse-previz-booth-wm-v5-052ef7eabf1746a2ad7d232837df8215',
    },
    {
        path: '/images/works/museo360.jpg',
        bigpath: '/images/works/g-museo360.jpg',
        title: 'Virtual Museum',
        category: '360 Virtual Tour',
        desc: 'A 3D 360º virtual tour museum for web art gallery.',
    },
    {
        path: '/images/works/peaktophouse.jpg',
        bigpath: '/images/works/g-peaktophouse.jpg',
        title: 'Peak top House',
        category: '3D Archviz',
        desc: 'A 3D archviz reconstruction of Peak top House in Barcelona.',
        link: 'https://www.artstation.com/artwork/EVlm4e',
    },
]

export const IMAGES_FRONTEND = [
    {
        path: '/images/works/mysteryman.jpg',
        bigpath: '/images/works/g-mysteryman.jpg',
        title: 'Mystery Man SCUMM Point & Click Video Game',
        category: 'Game Dev',
        desc: 'A point & click SCUMM video game.',
    },
    {
        path: '/images/works/web3.jpg',
        bigpath: '/images/works/web3.jpg',
        title: 'Personal Porfolios',
        category: 'HTML, CSS, JS',
        desc: 'A portfolio with tasty design.',
    },
    {
        path: '/images/works/web4.jpg',
        bigpath: '/images/works/web4.jpg',
        title: 'Universia Santander Shop',
        category: 'HTML, CSS, ASP.NET',
        desc: 'A shop web for book ecommerce.',
    },
    {
        path: '/images/works/web18.jpg',
        bigpath: '/images/works/web18.jpg',
        title: 'WMG Pharma',
        category: 'PHP, HTML, CSS',
        desc: 'German Cannabis Pharmaceutical',
    },
    {
        path: '/images/works/web5.jpg',
        bigpath: '/images/works/web5.jpg',
        title: 'Puntoblend Community',
        category: 'HTML, CSS, React',
        desc: 'Puntoblend Community portal.',
    },
    {
        path: '/images/works/web6.jpg',
        bigpath: '/images/works/web6.jpg',
        title: 'MedievalChess',
        category: 'HTML, SASS, React',
        desc: 'Based on chess but different moves and pieces.',
    },
    {
        path: '/images/works/web19.jpg',
        bigpath: '/images/works/web19.jpg',
        title: 'UNED University Shop',
        category: 'XTHML, CSS, ASP.NET',
        desc: 'Web eshop for UNED University.',
    },
    {
        path: '/images/works/web7.jpg',
        bigpath: '/images/works/web7.jpg',
        title: 'Travel Japan',
        category: 'HTML, CSS & JS',
        desc: 'Web portal with traveling articles.',
    },
    {
        path: '/images/works/web9.jpg',
        bigpath: '/images/works/web9.jpg',
        title: 'Shop Online',
        category: 'HTML, CSS & JS',
        desc: 'Shop web',
    },
    {
        path: '/images/works/web8.jpg',
        bigpath: '/images/works/web8.jpg',
        title: 'Bookmark Extension',
        category: 'HTML, CSS, JS',
        desc: 'Bookmark extension web',
    },
    {
        path: '/images/works/web11.jpg',
        bigpath: '/images/works/web11.jpg',
        title: 'Mini Game',
        category: 'HTML, CSS, React',
        desc: 'Web for childs to play little options game',
    },
    {
        path: '/images/works/web12.jpg',
        bigpath: '/images/works/web12.jpg',
        title: 'Bugdet Calculator',
        category: 'HTML, CSS, React',
        desc: 'Web for business to make budgets',
    },
    {
        path: '/images/works/web13.jpg',
        bigpath: '/images/works/web13.jpg',
        title: 'Temporal Job Search',
        category: 'HTML, CSS, React',
        desc: 'Web for job search',
    },
    {
        path: '/images/works/web14.jpg',
        bigpath: '/images/works/web14.jpg',
        title: 'Bumpho project',
        category: 'HTML, CSS, JS',
        desc: 'Internet fast search agreggator',
    },
    {
        path: '/images/works/web15.jpg',
        bigpath: '/images/works/web15.jpg',
        title: 'Old Portfolios',
        category: 'HTML, CSS, JS',
        desc: 'Old personal portfolio',
    },
    {
        path: '/images/works/web16.jpg',
        bigpath: '/images/works/web16.jpg',
        title: '3D Community web',
        category: 'HTML, CSS & JS',
        desc: 'Old community portfolio',
    },
    {
        path: '/images/works/web17.jpg',
        bigpath: '/images/works/web17.jpg',
        title: 'TrendsOnUnderground',
        category: 'HTML, CSS, JS',
        desc: 'Underground Trends Community',
    },
    {
        path: '/images/works/web10.jpg',
        bigpath: '/images/works/web10.jpg',
        title: 'Jokes page',
        category: 'HTML, CSS, JS',
        desc: 'Jokes page using several API',
    },
    {
        path: '/images/works/web1.jpg',
        bigpath: '/images/works/web1.jpg',
        title: 'LMDV Shop',
        category: 'HTML, CSS, JS',
        desc: 'A shop web for ecommerce.',
    },
    {
        path: '/images/works/web2.jpg',
        bigpath: '/images/works/web2.jpg',
        title: 'Lick Band Web',
        category: 'HTML, CSS, JS',
        desc: 'A shop web for a music band.',
    },
]

export const IMAGES_VIDEOVFX = [
    {
        path: '/images/works/projection.jpg',
        bigpath: '/images/works/g-projection.jpg',
        title: '3D Video Projection for Music Shows',
        category: '3D Projection',
        desc: '3D projection for music shows',
        video: 'gn06IhkXnOc',
    },
    {
        path: '/images/works/voluntariosaecc.jpg',
        bigpath: '/images/works/g-voluntariosaecc.jpg',
        title: 'Campaña Voluntariado AECC',
        category: 'Video Promo',
        desc: 'Campaña de Voluntariado AECC',
        video: 'tLqNmWTGJCI',
    },
    {
        path: '/images/works/promomotos.jpg',
        bigpath: '/images/works/g-promomotos.jpg',
        title: 'Motocross Tyler Bereman\'s with Andreu Lacondeguy',
        category: 'Video Promo',
        desc: 'Promo video for Tyler Bereman\'s Motocross',
        video: 'GuPy_VyEqac',
    },
    {
        path: '/images/works/operaprima.jpg',
        bigpath: '/images/works/g-operaprima.jpg',
        title: 'Opera Prima Documentary',
        category: 'TV Documentary',
        desc: 'Documentary about the first opera play in a special needs school in Spain',
        video: 'pqBJiJ4GPf0',
    },
    {
        path: '/images/works/buenafuente.jpg',
        bigpath: '/images/works/g-buenafuente.jpg',
        title: 'TV Sketches',
        category: 'Video & VFX',
        desc: 'A couple of humour sketches, mixing chroma video footage from Andreu Buenafuente\'s En El Aire late night show.',
        video: 'tTobaqm1YHk',
    },
    {
        path: '/images/works/aguilabook.jpg',
        bigpath: '/images/works/g-aguilabook.jpg',
        title: 'Wild Eagle',
        category: 'Photobook',
        desc: 'Photo report about eagles from wildlife',
    },
    {
        path: '/images/works/amsterdambikes.jpg',
        bigpath: '/images/works/g-amsterdambikes.jpg',
        title: 'Amsterdam Travel',
        category: 'Photobook',
        desc: 'Amsterdam travel photoshoot',
    },
    {
        path: '/images/works/promovolkswagen.jpg',
        bigpath: '/images/works/g-promovolkswagen.jpg',
        title: 'Volkswagen Internal Promo videos',
        category: 'Video, Mograph & Sound',
        desc: 'Volkswagen internal promo videos',
    },
    {
        path: '/images/works/promoliberation.jpg',
        bigpath: '/images/works/g-promoliberation.jpg',
        title: 'Liberation Day video event on Netherlands',
        category: 'Video & VFX',
        desc: 'Video event for Liberation Day on Netherlands',
        video: 'PeurByeXLCs',
    },
    {
        path: '/images/works/paseopirineos.jpg',
        bigpath: '/images/works/g-paseopirineos.jpg',
        title: 'Prinieos Travel',
        category: 'Photobook',
        desc: 'Traveling nature lifestyle photo report on wildlife',
    },
    {
        path: '/images/works/altamirano.jpg',
        bigpath: '/images/works/g-altamirano.jpg',
        title: 'Altamirano\'s Downhill',
        category: 'Video Promo',
        desc: 'Video promotion for Altamirano\'s Downhill Team & Shop.',
        video: 'iVuMXaB1egk',
    },
    {
        path: '/images/works/bmxartur.jpg',
        bigpath: '/images/works/g-bmxartur.jpg',
        title: 'Artur Gröbli BMX',
        category: 'Video Sport',
        desc: 'BMX Sport video of biker Artur Gröbli.',
        video: 'zAY9Fl4EZ2A',
    },
    {
        path: '/images/works/barconerja.jpg',
        bigpath: '/images/works/g-barconerja.jpg',
        title: 'Nerja Ship',
        category: 'Photo Report',
        desc: 'Photo report from the Spain\'s south coast.',
    },
    {
        path: '/images/works/bca.jpg',
        bigpath: '/images/works/g-bca.jpg',
        title: 'BCA Tutorials',
        category: 'Video Production',
        desc: 'A series of video tutorials focused to B2B clients.',
        video: 'iXSwcAK25T0',
    },
    {
        path: '/images/works/gondwana1.jpg',
        bigpath: '/images/works/g-gondwana1.jpg',
        title: 'Gondwana Album',
        category: 'Photoshoot',
        desc: 'Photo session for the Gondwana album book.',
    },
    {
        path: '/images/works/timelapses.jpg',
        bigpath: '/images/works/g-timelapses.jpg',
        title: 'Nightsky Timelapses',
        category: 'Video & VFX',
        desc: 'A series of timelapses from the night sky.',
        video: 'NpI7Xk0FpXk',
    },
    {
        path: '/images/works/bodacostumbrista.jpg',
        bigpath: '/images/works/g-bodacostumbrista.jpg',
        title: 'Traditional Events',
        category: 'Event Video & Photo',
        desc: 'Photobooks for Weddings and other family events with a different point of view.',
        link: 'https://500px.com/photo/39759430/Bentley-Wedding-by-Oscar-Nebe-Abad?ctx_page=1&from=user&user_id=926045',
    },
    {
        path: '/images/works/bookperra.jpg',
        bigpath: '/images/works/g-bookperra.jpg',
        title: 'Dog Portrait',
        category: 'Animal Photoshoot',
        desc: 'Animal photobooks with natural, posed and funny styles.',
    },
    {
        path: '/images/works/bikecampo.jpg',
        bigpath: '/images/works/g-bikecampo.jpg',
        title: 'A Bike\'s Day',
        category: 'Lifestyle Photo',
        desc: 'An example of hundreds of lifestyle photo sesions for branding.',
    },
    {
        path: '/images/works/caballoarbol.jpg',
        bigpath: '/images/works/g-caballoarbol.jpg',
        title: 'Traditional Farming',
        category: 'Lifestyle Photo',
        desc: 'A photo reportage about traditional farming at Pyrenees.',
    },
    {
        path: '/images/works/caballoretrato.jpg',
        bigpath: '/images/works/g-caballoretrato.jpg',
        title: 'Millan\'s Horse',
        category: 'Lifestyle Photo',
        desc: 'Photobook with a funny horse.',
    },
    {
        path: '/images/works/caprichogaudi.jpg',
        bigpath: '/images/works/g-caprichogaudi.jpg',
        title: 'Capricho de Gaudí',
        category: 'Lifestyle Photo',
        desc: 'The winner HDR picture from the Capricho de Gaudí building photography contest, placed in Comillas, Cantabria.',
    },
    {
        path: '/images/works/catalogocolonia.jpg',
        bigpath: '/images/works/g-catalogocolonia.jpg',
        title: 'Dirty English',
        category: 'Product Photoshoot',
        desc: 'Photo catalog for Dirty English fragance by Juicy Couture.',
    },
    {
        path: '/images/works/catalogopocketmgz.jpg',
        bigpath: '/images/works/g-catalogopocketmgz.jpg',
        title: 'Glasses Catalog',
        category: 'Product Photoshoot',
        desc: 'A lifestyle photoshoot for a glasses product placement for Pocket Magazine.',
    },
    {
        path: '/images/works/cerroskate.jpg',
        bigpath: '/images/works/g-cerroskate.jpg',
        title: 'Cerro\'s Skate',
        category: 'Video Promo',
        desc: 'A video promo for Jorge Cerro freestyle skater.',
        video: 'KscjxzJVwIQ',
    },
    {
        path: '/images/works/chema1.jpg',
        bigpath: '/images/works/g-chema1.jpg',
        title: 'Chema Sales Booklet',
        category: 'Photo / Booklet',
        desc: 'Photoshoot, editing and design of the CD booklet for Chema Sales.',
    },
    {
        path: '/images/works/chevrolet.jpg',
        bigpath: '/images/works/g-chevrolet.jpg',
        title: 'Chevrolet Bel Air',
        category: 'Lifestyle Photo',
        desc: 'Classic cars photoshoots for enthusiast owners.',
    },
    {
        path: '/images/works/chicharrocd.jpg',
        bigpath: '/images/works/g-chicharrocd.jpg',
        title: '\'La Caja de las Ánimas\'',
        category: 'Photo / Booklet',
        desc: 'Photoshoot and booklet design for \'La Caja de las Ánimas\' album from Guillermo Chicharro.',
    },
    {
        path: '/images/works/promoartist.jpg',
        bigpath: '/images/works/g-promoartist.jpg',
        title: 'Promo Artist',
        category: 'Video Promo',
        desc: 'A video promo for the artist Lucas Dias.',
        video: 'JCejxBLZOaM'
    },
    {
        path: '/images/works/chicharrostudio.jpg',
        bigpath: '/images/works/g-chicharrostudio.jpg',
        title: 'Chicharro\'s Studio',
        category: 'Pressbook Photo',
        desc: 'Photoshoots of different music studios like KMC or Lizard Studios.',
    },
    {
        path: '/images/works/promotaurus.jpg',
        bigpath: '/images/works/g-promotaurus.jpg',
        title: 'Guille Chicharro Promo Taurus Amplifiers',
        category: 'Video Promo',
        desc: 'Video promo for Taurus Amplifiers endorser Guille Chicharro.',
        video: 'n6bI3xo5Clw',
    },
    {
        path: '/images/works/comillas.jpg',
        bigpath: '/images/works/g-comillas.jpg',
        title: 'Shore Landscape',
        category: 'Natural Photoshoot',
        desc: 'HDR Photoshoots of landscapes and natural views.',
    },
    {
        path: '/images/works/composicionfondos.jpg',
        bigpath: '/images/works/g-composicionfondos.jpg',
        title: 'Background replacement',
        category: 'Video / VFX',
        desc: 'Background replacements for films, shortfilms and tv shows.',
    },
    {
        path: '/images/works/deilamanita.jpg',
        bigpath: '/images/works/g-deilamanita.jpg',
        title: '\'Deil\' Shortfilm',
        category: 'Video Shortfilm',
        desc: 'Color correction for award-winning DEIL shortfilm by Amanita Films.',
        link: 'https://vimeo.com/71738108',
    },
    {
        path: '/images/works/docuhealingnotes.jpg',
        bigpath: '/images/works/g-docuhealingnotes.jpg',
        title: '\'The Healing Notes\'',
        category: 'Video Documentary',
        desc: 'Color correction for award-winning DEIL shortfilm by Amanita Films.',
    },
    {
        path: '/images/works/dorange.jpg',
        bigpath: '/images/works/g-dorange.jpg',
        title: 'd\'Orange Unplugged',
        category: 'Video Music Clip',
        desc: 'Unplugged song videoclip for dOrange band.',
    },
    {
        path: '/images/works/dronefreestyle.jpg',
        bigpath: '/images/works/g-dronefreestyle.jpg',
        title: 'Drone Freestyle',
        category: 'Aerial Video',
        desc: 'FPV Drone Freestyling videos.',
        video: 'sjQB4lGCV9c',
    },
    {
        path: '/images/works/paloma.jpg',
        bigpath: '/images/works/g-paloma.jpg',
        title: 'Street Photography',
        category: 'Lifestyle Photo',
        desc: 'Street photography of people and urban landscapes.',
    },
    {
        path: '/images/works/eventpeople.jpg',
        bigpath: '/images/works/g-eventpeople.jpg',
        title: 'Family Events',
        category: 'Photoshoot',
        desc: 'Stylized photo books from events.',
    },
    {
        path: '/images/works/finistere.jpg',
        bigpath: '/images/works/g-finistere.jpg',
        title: 'Finisterre\'s Cape',
        category: 'Photoshoot',
        desc: 'Photo reportage from the \'end of the earth\', Finisterre.',
    },
    {
        path: '/images/works/freebord.jpg',
        bigpath: '/images/works/g-freebord.jpg',
        title: 'Freebord Skates',
        category: 'Video Promo',
        desc: 'An inspirational video promo for the Freebord skates user experience.',
        video: 'L_17eGLCfSY'
    },
    {
        path: '/images/works/gondwana2.jpg',
        bigpath: '/images/works/g-gondwana2.jpg',
        title: 'Musician Portrait',
        category: 'Photo / Booklet',
        desc: 'Photoshoots for mucisians book.',
    },
    {
        path: '/images/works/greentotem1.jpg',
        bigpath: '/images/works/g-greentotem1.jpg',
        title: 'The Green Totem I',
        category: 'Motion Graphics',
        desc: 'Content depending intro mo-graph animations..',
    },
    {
        path: '/images/works/greentotem2.jpg',
        bigpath: '/images/works/g-greentotem2.jpg',
        title: 'The Green Totem II',
        category: 'Motion Graphics',
        desc: 'Content depending intro mo-graph animations..',
    },
    {
        path: '/images/works/greentotem3.jpg',
        bigpath: '/images/works/g-greentotem3.jpg',
        title: 'The Green Totem III',
        category: 'Motion Graphics',
        desc: 'Content depending intro mo-graph animations..',
    },
    {
        path: '/images/works/haitioptimista.jpg',
        bigpath: '/images/works/g-haitioptimista.jpg',
        title: 'Haiti Optimista',
        category: 'Photoshoot',
        desc: 'Mixed cameras photo experiment from Haiti\'s childrens for El Pais newspaper and other partners like AECID and Samsung.',
        link: 'https://elpais.com/sociedad/2013/01/10/album/1357850758_982739.html',
    },
    {
        path: '/images/works/mrelehaiti.jpg',
        bigpath: '/images/works/g-mrelehaiti.jpg',
        title: 'M\'Rele Haiti',
        category: 'Video Documentary',
        desc: 'A film documentary in Port Prince and Jacmel in Haiti about childrens life after earthquake.',
        video: 'tN4_Ubq0Ln4',
    },
    {
        path: '/images/works/incubusdig.jpg',
        bigpath: '/images/works/g-incubusdig.jpg',
        title: 'Incubus - Dig',
        category: 'Videoclip VFX',
        desc: 'A 3D tracking and replacement for Dig\'s videoclip from Incubus band.',
    },
    {
        path: '/images/works/introspannabis.jpg',
        bigpath: '/images/works/g-introspannabis.jpg',
        title: 'Fairs Coverage',
        category: 'Video Production',
        desc: 'Fairs full coverage for social networks, filming, editing and mo-grap.',
        video: 'IV975aM4Czw',
    },
    {
        path: '/images/works/kalifishtanks.jpg',
        bigpath: '/images/works/g-kalifishtanks.jpg',
        title: 'Kali\'s Fishtanks',
        category: 'Video Book',
        desc: 'Video book of the microbiologist Carlos San Juan\'s Fishtanks with sea and interior ecosystems.',
    },
    {
        path: '/images/works/labrujuladeeva.jpg',
        bigpath: '/images/works/g-labrujuladeeva.jpg',
        title: 'Eva\'s Compass',
        category: 'Video Shortfilm',
        desc: 'Video edit, color, vfx and sounding of Cristina Sardon\'s \'Eva\'s Compass\' shortfilm.',
    },
]